library(ISLR)
data = Weekly
head(data)
summary(data)
pairs(data)
plot(data$Volume, ylab = 'Shares')
cor(data[-9])
bm.full = glm(Direction ~ . - Year - Today, data = data, family = 'binomial')
summary(bm.full)
bm.full.probs = predict(bm.full, type = 'response')
bm.full.pred = rep('Down', 1089)
bm.full.pred[bm.full.probs > 0.5] = 'Up'
table(bm.full.pred, data$Direction)
mean(bm.full.pred == data$Direction)
test = (data$Year < 2009)
bm.fit = glm(Direction ~ Lag2, data = data, subset = test, family = 'binomial')
summary(bm.fit)
bm.probs = predict(bm.fit, data[!test, ], type = 'response')
bm.pred = rep('Down', dim(data[!test, ])[1])
bm.pred[bm.probs > 0.5] = 'Up'
table(bm.pred, data[!test, ]$Direction)
mean(bm.pred == data[!test, ]$Direction)
mean(data[!test, ]$Direction == 'Up')
library(MASS)
gm.fit = lda(Direction ~ Lag2, data = data, subset = test)
gm.fit
gm.pred = predict(gm.fit, data[!test, ])
table(gm.pred$class, data[!test, ]$Direction)
mean(gm.pred$class == data[!test, ]$Direction)
lm.fit = qda(Direction ~ Lag2, data = data, subset = test)
lm.fit
lm.pred = predict(lm.fit, data[!test, ])
table(lm.pred$class, data[!test, ]$Direction)
mean(lm.pred$class == data[!test, ]$Direction)
library(class)
train.x = data.frame(data[test, ]$Lag2)
test.x = data.frame(data[!test, ]$Lag2)
train.Direction = data[test, ]$Direction
set.seed(1)
clus.pred = knn(train.x, test.x, train.Direction, k = 1)
table(clus.pred, data[!test, ]$Direction)
mean(clus.pred == data[!test, ]$Direction)
library(e1071)
library(caTools)
library(caret)
train.x = data.frame(data[test, ]$Lag2)
test.x = data.frame(data[!test, ]$Lag2)
train.Direction = data[test, ]$Direction
naive.fit = naiveBayes(Direction ~ Lag2, data = train.x)
naive.fit
naive.pred = predict(naive.fit, data[!test, ])
table(naive.pred, data[!test, ]$Direction)
mean(naive.pred == data[!test, ]$Direction)
